name: Deploy to uberspace

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: "{{ secrets.UBSERPACE_SSH_PRIVATE }}"
          REMOTE_HOST: tritton.uberspace.de
          REMOTE_USER: "{{ secrets.UBERSPACE_SSH_USER }}"
          TARGET: "/home/{{ secrets.UBERSPACE_SSH_USER }}/html"

